# Predicting Customer Purchase Amounts Using Multivariable Linear Regression

In this notebook, we examine shopping data of a Black Friday sale to assess what influences the amount of money a customer spends. Our method, known as multivariate linear regression, helps us to estimate the amount of purchases new customers will make based on the trends in the training data. The first stage is to clean and prepare the training dataset. Then we construct the model and lastly use it to make predictions of the purchase amounts of the test data, in which the purchase values are missing.

In [1]:
# Importing libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
# Reading the file using 
df_train = pd.read_csv(r"C:\Users\Savi Hegde\OneDrive\Desktop\Final Data Analysis - Savi\train.csv")

In [4]:
# The below code helps us to get to know about the data, if there are any missing values, data types and what are features available.
df_train.head(5)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969

In [5]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     550068 non-null  int64
 1   Product_ID                  550068 non-null  object
 2   Gender                      550068 non-null  object
 3   Age                         550068 non-null  object
 4   Occupation                  550068 non-null  int64
 5   City_Category               550068 non-null  object
 6   Stay_In_Current_City_Years  550068 non-null  object
 7   Marital_Status              550068 non-null  int64
 8   Product_Category_1          550068 non-null  int64
 9   Product_Category_2          376430 non-null  float64
 10  Product_Category_3          166821 non-null  float64
 11  Purchase                    550068 non-null  int64
dtypes: float64(2), int64(5), object(5)
memory usage: 50.4+ MB

In [6]:
df_train.describe()

,User_ID,Occupation,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
count,5.500680e+05,550068.000000,550068.000000,550068.000000,376430.000000,166821.000000,550068.000000
mean,1.003029e+06,8.076707,0.409653,5.404270,9.842329,12.668243,9263.968713
std,1.727592e+03,6.522660,0.491770,3.936211,5.086590,4.125338,5023.065394
min,1.000001e+06,0.000000,0.000000,1.000000,2.000000,3.000000,12.000000
25%,1.001516e+06,2.000000,0.000000,1.000000,5.000000,9.000000,5823.000000
50%,1.003077e+06,7.000000,0.000000,5.000000,9.000000,14.000000,8047.000000
75%,1.004478e+06,14.000000,1.000000,8.000000,15.000000,16.000000,12054.000000
max,1.006040e+06,20.000000,1.000000,20.000000,18.000000,18.000000,23961.000000

In [7]:
df_train.shape

(550068, 12)

In [8]:
df_train.drop(['User_ID'], axis=1, inplace=True)

In [10]:
df_train.head(5)

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969

# Data Cleaning: The data was cleaned with maping the "gender", "Age", "City". Also dropped "user_ID", "Product_ID".

In [11]:
df_train['Gender'] = df_train['Gender'].map({'F': 0, 'M': 1})

In [12]:
df_train.head(5)

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,P00069042,0,0-17,10,A,2,0,3,NaN,NaN,8370
1,P00248942,0,0-17,10,A,2,0,1,6.0,14.0,15200
2,P00087842,0,0-17,10,A,2,0,12,NaN,NaN,1422
3,P00085442,0,0-17,10,A,2,0,12,14.0,NaN,1057
4,P00285442,1,55+,16,C,4+,0,8,NaN,NaN,7969

In [13]:
df_train.drop(['Product_ID'], axis=1, inplace=True)

In [14]:
df_train.head(5)

,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,0,0-17,10,A,2,0,3,NaN,NaN,8370
1,0,0-17,10,A,2,0,1,6.0,14.0,15200
2,0,0-17,10,A,2,0,12,NaN,NaN,1422
3,0,0-17,10,A,2,0,12,14.0,NaN,1057
4,1,55+,16,C,4+,0,8,NaN,NaN,7969

In [15]:
df_train['Age'].unique()

array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

In [16]:
df_train.loc[:, 'Age'] = df_train['Age'].map({
    '0-17':0, '18-25':1, '26-35':2, '36-45':3,
    '46-50':4, '51-55':5, '55+':6
})

In [17]:
df_train.head(5)

,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,0,0,10,A,2,0,3,NaN,NaN,8370
1,0,0,10,A,2,0,1,6.0,14.0,15200
2,0,0,10,A,2,0,12,NaN,NaN,1422
3,0,0,10,A,2,0,12,14.0,NaN,1057
4,1,6,16,C,4+,0,8,NaN,NaN,7969

In [18]:
df_train['City_Category'].unique()

array(['A', 'C', 'B'], dtype=object)

In [19]:
from sklearn.preprocessing import LabelEncoder
lbl=LabelEncoder()
df_train['City_Category']=lbl.fit_transform(df_train['City_Category'])

In [20]:
df_train.head(5)

,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,0,0,10,0,2,0,3,NaN,NaN,8370
1,0,0,10,0,2,0,1,6.0,14.0,15200
2,0,0,10,0,2,0,12,NaN,NaN,1422
3,0,0,10,0,2,0,12,14.0,NaN,1057
4,1,6,16,2,4+,0,8,NaN,NaN,7969

In [23]:
df_train['Stay_In_Current_City_Years'] = df_train['Stay_In_Current_City_Years'].str.replace('+', '')
df_train['Stay_In_Current_City_Years']=df_train['Stay_In_Current_City_Years'].astype(int)

In [24]:
df_train.head(5)

,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,0,0,10,0,2,0,3,NaN,NaN,8370
1,0,0,10,0,2,0,1,6.0,14.0,15200
2,0,0,10,0,2,0,12,NaN,NaN,1422
3,0,0,10,0,2,0,12,14.0,NaN,1057
4,1,6,16,2,4,0,8,NaN,NaN,7969

In [26]:
df_train['Age']=df_train['Age'].astype(int)

In [27]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 10 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Gender                      550068 non-null  int64
 1   Age                         550068 non-null  int64
 2   Occupation                  550068 non-null  int64
 3   City_Category               550068 non-null  int64
 4   Stay_In_Current_City_Years  550068 non-null  int64
 5   Marital_Status              550068 non-null  int64
 6   Product_Category_1          550068 non-null  int64
 7   Product_Category_2          376430 non-null  float64
 8   Product_Category_3          166821 non-null  float64
 9   Purchase                    550068 non-null  int64
dtypes: float64(2), int64(8)
memory usage: 42.0 MB

In [28]:
df_train.isnull().sum()

Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

# Data was with missing values and filled with "0" to get the accurate results

In [29]:
df_train['Product_Category_2']=df_train['Product_Category_2'].fillna(0)
df_train['Product_Category_3']=df_train['Product_Category_3'].fillna(0)

In [32]:
df_train.head(5)

,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,0,0,10,0,2,0,3,0.0,0.0,8370
1,0,0,10,0,2,0,1,6.0,14.0,15200
2,0,0,10,0,2,0,12,0.0,0.0,1422
3,0,0,10,0,2,0,12,14.0,0.0,1057
4,1,6,16,2,4,0,8,0.0,0.0,7969

In [30]:
df_train.isnull().sum()

Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
Purchase                      0
dtype: int64

In [31]:
df_train.columns

Index(['Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

# Data modeling using the train set alone by splitting it into train/test using linear regression

In [35]:
X = df_train.drop('Purchase', axis=1)
y = df_train['Purchase']

In [37]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.2,    
    random_state=42     
)

In [39]:
X_train.shape, X_test.shape

((440054, 9), (110014, 9))

In [41]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [43]:
y_pred = model.predict(X_test)

In [44]:
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("R² Score:", r2)
print("RMSE:", rmse)

R² Score: 0.15099132139602234
RMSE: 4618.695144021097

In [45]:
y_pred = model.predict(X_test)

In [46]:
comparison = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred
})

comparison.head(10)

   Actual     Predicted
0   19142  13261.491858
1   15513  12371.880477
2    7802   7212.528053
3   15455  12300.962909
4    4492  10758.914856
5    6965  10414.205362
6    8763   8913.685073
7   19347   9792.957339
8    7017   9419.601181
9   15594  10618.741151

In [47]:
comparison['Error'] = comparison['Actual'] - comparison['Predicted']
comparison.sample(4)

       Actual     Predicted        Error
29245    7081   8713.834091 -1632.834091
69275    7163   8903.159124 -1740.159124
81749    8046  10682.995380 -2636.995380
95530    8685   9595.069045  -910.069045

# Data prediction for the "Test set data" followed all the same steps applied for "Train set data"

In [53]:
df_test = pd.read_csv(r"C:\Users\Savi Hegde\OneDrive\Desktop\Final Data Analysis - Savi\test.csv")

In [54]:
df_test.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3'],
      dtype='object')

In [55]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233599 entries, 0 to 233598
Data columns (total 11 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     233599 non-null  int64
 1   Product_ID                  233599 non-null  object
 2   Gender                      233599 non-null  object
 3   Age                         233599 non-null  object
 4   Occupation                  233599 non-null  int64
 5   City_Category               233599 non-null  object
 6   Stay_In_Current_City_Years  233599 non-null  object
 7   Marital_Status              233599 non-null  int64
 8   Product_Category_1          233599 non-null  int64
 9   Product_Category_2          161255 non-null  float64
 10  Product_Category_3          71037 non-null   float64
dtypes: float64(2), int64(4), object(5)
memory usage: 19.6+ MB

In [56]:
df_test.drop(['User_ID', 'Product_ID'], axis=1, inplace=True)

In [57]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233599 entries, 0 to 233598
Data columns (total 9 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Gender                      233599 non-null  object
 1   Age                         233599 non-null  object
 2   Occupation                  233599 non-null  int64
 3   City_Category               233599 non-null  object
 4   Stay_In_Current_City_Years  233599 non-null  object
 5   Marital_Status              233599 non-null  int64
 6   Product_Category_1          233599 non-null  int64
 7   Product_Category_2          161255 non-null  float64
 8   Product_Category_3          71037 non-null   float64
dtypes: float64(2), int64(3), object(4)
memory usage: 16.0+ MB

In [59]:
df_test.head()

,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
0,M,46-50,7,B,2,1,1,11.0,NaN
1,M,26-35,17,C,0,0,3,5.0,NaN
2,F,36-45,1,B,4+,1,5,14.0,NaN
3,F,36-45,1,B,4+,1,4,9.0,NaN
4,F,26-35,1,C,1,0,4,5.0,12.0

In [60]:
df_test['Gender'] = df_test['Gender'].map({'F': 0, 'M': 1})

In [61]:
df_test.head()

,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
0,1,46-50,7,B,2,1,1,11.0,NaN
1,1,26-35,17,C,0,0,3,5.0,NaN
2,0,36-45,1,B,4+,1,5,14.0,NaN
3,0,36-45,1,B,4+,1,4,9.0,NaN
4,0,26-35,1,C,1,0,4,5.0,12.0

In [62]:
df_test['Age'] = df_test['Age'].map({
    '0-17':0, '18-25':1, '26-35':2, '36-45':3,
    '46-50':4, '51-55':5, '55+':6
})

In [63]:
df_test.head()

,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
0,1,4,7,B,2,1,1,11.0,NaN
1,1,2,17,C,0,0,3,5.0,NaN
2,0,3,1,B,4+,1,5,14.0,NaN
3,0,3,1,B,4+,1,4,9.0,NaN
4,0,2,1,C,1,0,4,5.0,12.0

In [64]:
df_test['City_Category'].unique()

array(['B', 'C', 'A'], dtype=object)

In [65]:
city_map = {'A': 0, 'B': 1, 'C': 2}
df_test['City_Category'] = df_test['City_Category'].map(city_map)

In [66]:
df_test.head(5)

,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
0,1,4,7,1,2,1,1,11.0,NaN
1,1,2,17,2,0,0,3,5.0,NaN
2,0,3,1,1,4+,1,5,14.0,NaN
3,0,3,1,1,4+,1,4,9.0,NaN
4,0,2,1,2,1,0,4,5.0,12.0

In [67]:
df_test['Stay_In_Current_City_Years'] = df_test['Stay_In_Current_City_Years'].str.replace('+', '')
df_test['Stay_In_Current_City_Years']=df_test['Stay_In_Current_City_Years'].astype(int)

In [68]:
df_test.head(5)

,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
0,1,4,7,1,2,1,1,11.0,NaN
1,1,2,17,2,0,0,3,5.0,NaN
2,0,3,1,1,4,1,5,14.0,NaN
3,0,3,1,1,4,1,4,9.0,NaN
4,0,2,1,2,1,0,4,5.0,12.0

In [69]:
df_test.isnull().sum()

Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2             72344
Product_Category_3            162562
dtype: int64

In [70]:
df_test['Product_Category_2']=df_test['Product_Category_2'].fillna(0)
df_test['Product_Category_3']=df_test['Product_Category_3'].fillna(0)

In [71]:
df_test.isnull().sum()

Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
dtype: int64

In [72]:
predictions = model.predict(df_test)

In [73]:
df_test['Purchase'] = predictions

In [74]:
df_test = df_test[X_train.columns]

In [75]:
test_predictions = model.predict(df_test)

In [76]:
output = pd.DataFrame({
    'Purchase': test_predictions
})

In [77]:
test_predictions = model.predict(df_test)

In [78]:
pred_df = pd.DataFrame(test_predictions, columns=['Purchase'])

In [79]:
pred_df.head()

       Purchase
0  10531.540783
1   9949.249248
2   8580.277132
3   8863.631685
4  10776.264196

In [80]:
df_test_with_predictions = df_test.copy()
df_test_with_predictions['Predicted_Purchase'] = test_predictions

In [81]:
df_test_with_predictions.head(10)

,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Predicted_Purchase
0,1,4,7,1,2,1,1,11.0,0.0,10531.540783
1,1,2,17,2,0,0,3,5.0,0.0,9949.249248
2,0,3,1,1,4,1,5,14.0,0.0,8580.277132
3,0,3,1,1,4,1,4,9.0,0.0,8863.631685
4,0,2,1,2,1,0,4,5.0,12.0,10776.264196
5,1,4,1,2,3,1,2,3.0,15.0,12530.323110
6,1,4,1,2,3,1,1,11.0,15.0,12982.704286
7,1,4,1,2,3,1,2,4.0,9.0,11678.921687
8,1,2,7,0,1,0,10,13.0,16.0,9244.994304
9,1,1,15,0,4,0,5,14.0,0.0,8656.415116